/* @author Ravindra Singh 29/05/2022 
 * Class for handelling constants values and consolidate Custom labels values
 *  
*/
public class MissingWebUserConstantClass {
    
    // Boolean values
    public static final Boolean TRUE_VALUE = true;
    public static final Boolean FALSE_VALUE = false;
    
    //End points
    Public static final String	MISSING_VALUE_ENDPOINT_GET = 'https://jsonplaceholder.typicode.com/users';
    Public static final String	GET_METHOD_VALUE	=	'GET';
    
    
    //Logical Values Hardcoding
    Public static final String	S_ID	=	'id';
   	Public static final String	S_WEBID	=	'webId';
    Public static final String	S_NAME	=	'name';

}